QUESTIONS:
si on transforme notre kernel de base en un kernel multi symétrique on change l'effet du kernel ?
on devrait étudier le lien entre le kernel initial et celui transformé pour voir si ils ont les mêmes actions

IMPORT DES FONCTIONS IMPORTANTES

In [69]:
import torch
import torch.nn.functional as F
import torch.nn.utils.parametrize as parametrize
import numpy as np

TEST SUR LE ROT90

In [70]:
#TEST SUR LE TORCH.RAND
Input=torch.rand(2,2)
Input3=Input.view(1,1,2,2)
Input2=torch.rand(1,1,2,2)
Input4=Input2.view(2,2)
rot=torch.rot90(Input2,1,[1,0])
print(Input2)
print(Input4)

tensor([[[[0.9754, 0.2109],
          [0.2631, 0.0666]]]])
tensor([[0.9754, 0.2109],
        [0.2631, 0.0666]])


In [71]:
Input = torch.rand(5,5)
print(Input)
a=torch.rot90(Input, 1, [0, 1])
print(a)

#a = torch.arange(8).view(2, 2, 2)
#print(x)
#a=torch.rot90(x, 1, [1, 2])
#print(a)


tensor([[0.5825, 0.9527, 0.3283, 0.1077, 0.8136],
        [0.5145, 0.3963, 0.4640, 0.3469, 0.5858],
        [0.6698, 0.5007, 0.9850, 0.7541, 0.0658],
        [0.4420, 0.9661, 0.7239, 0.6487, 0.2302],
        [0.9928, 0.1655, 0.0800, 0.9950, 0.5624]])
tensor([[0.8136, 0.5858, 0.0658, 0.2302, 0.5624],
        [0.1077, 0.3469, 0.7541, 0.6487, 0.9950],
        [0.3283, 0.4640, 0.9850, 0.7239, 0.0800],
        [0.9527, 0.3963, 0.5007, 0.9661, 0.1655],
        [0.5825, 0.5145, 0.6698, 0.4420, 0.9928]])


TRANSFORMER UNE MATRICE EN UNE MATRICE SYMETRIQUE DE TOUTES DIRECTIONS

In [72]:
def invar(X):
    a=torch.rot90(X, 1, [1,0])
    b=torch.rot90(a, 1, [1,0])
    c=torch.rot90(b, 1, [1,0])
    d= X+a+b+c
    return(d)



#K =  torch.Tensor([[1 ,0, -10],[2, 0 ,-2], [1, 0 ,-1]])
#K1=np.random.rand(3,3)
#K3 =  torch.Tensor(K1)
#K4=invar(K3)
#print(K4)



Compréhension des axes à rotater

In [73]:
#K =  torch.Tensor([[100 ,0, 0, 0,0 ],[0, 100 ,0, 0,0], [0, 0 ,100,0,0],[0, 0 ,0,100,0],[0, 0 ,0,0,100]])
#print(K)
#a=torch.rot90(K, 1, [1,0])
#print(a)
Input = torch.randn(5,5)
#print(Input)
Input2=torch.rot90(Input, 1, [1,0])
print(Input)
print(Input2)
print(Input==Input2)

tensor([[ 1.3088,  1.1696,  0.6814,  0.9831,  0.5939],
        [ 0.7316, -0.7684,  0.8788,  0.2312, -0.5189],
        [-1.3253,  1.2072,  0.1817, -0.0141,  0.6427],
        [ 0.3280, -0.6847,  1.3069, -0.1267,  0.2586],
        [ 0.1767, -1.9640,  1.6575,  0.1101, -1.4928]])
tensor([[ 0.1767,  0.3280, -1.3253,  0.7316,  1.3088],
        [-1.9640, -0.6847,  1.2072, -0.7684,  1.1696],
        [ 1.6575,  1.3069,  0.1817,  0.8788,  0.6814],
        [ 0.1101, -0.1267, -0.0141,  0.2312,  0.9831],
        [-1.4928,  0.2586,  0.6427, -0.5189,  0.5939]])
tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False,  True, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])


TEST CONV2D

In [74]:
Input = torch.rand(1,1,5,5)
#print(Input)
K =  torch.Tensor([[[1 ,0, -1],[2, 0 ,-10], [1, 0 ,-1]],[[1 ,0, -1],[2, 0 ,-10], [1, 0 ,-1]]])
#K=invar(K)
#K=invar(K)
print(K)
Kernel = K.view(2, 1, 3, 3)
print(Kernel)
output = F.conv2d(Input, Kernel)
#print(output)


tensor([[[  1.,   0.,  -1.],
         [  2.,   0., -10.],
         [  1.,   0.,  -1.]],

        [[  1.,   0.,  -1.],
         [  2.,   0., -10.],
         [  1.,   0.,  -1.]]])
tensor([[[[  1.,   0.,  -1.],
          [  2.,   0., -10.],
          [  1.,   0.,  -1.]]],


        [[[  1.,   0.,  -1.],
          [  2.,   0., -10.],
          [  1.,   0.,  -1.]]]])


cnn UNE COUCHE AVEC UNE IMAGE EN ENTREE

In [75]:
#Initialisation des images d'entrée et des kernels

#IMAGE DROITE
Input=torch.rand(5,5)
Input1 = Input.view(1,1,5,5)
print(Input1)


#IMAGE TOURNEE
Input2=torch.rot90(Input, 1, [1,0])
Input3=Input2.view(1,1,5,5)
print(Input3)


#KERNEL
K=np.random.rand(3,3)
K1 =  torch.Tensor(K)
K2=invar(K1)
Kernel=K2.view(1,1,3,3)
print(Kernel)




tensor([[[[0.4758, 0.9870, 0.0251, 0.5356, 0.1434],
          [0.7508, 0.5020, 0.4327, 0.1075, 0.6955],
          [0.3193, 0.8840, 0.1034, 0.5053, 0.1011],
          [0.1812, 0.1135, 0.9581, 0.1798, 0.0447],
          [0.6730, 0.4051, 0.8607, 0.0169, 0.8984]]]])
tensor([[[[0.6730, 0.1812, 0.3193, 0.7508, 0.4758],
          [0.4051, 0.1135, 0.8840, 0.5020, 0.9870],
          [0.8607, 0.9581, 0.1034, 0.4327, 0.0251],
          [0.0169, 0.1798, 0.5053, 0.1075, 0.5356],
          [0.8984, 0.0447, 0.1011, 0.6955, 0.1434]]]])
tensor([[[[2.5276, 1.9136, 2.5276],
          [1.9136, 3.3778, 1.9136],
          [2.5276, 1.9136, 2.5276]]]])


In [76]:
#Input1 = torch.randn(1,1,5,5)
#rint(Input1)
#Input2=torch.rot90(Input1, 1, [1,0])
#print(Input2)
#print(Input2)  # création de 2 inputs avec une rotation de 90° entre eux

#print(Input==Input2)
#K=np.random.rand(3,3)
#K1 =  torch.Tensor(K)
#K2=invar(K1)
#print(K2)

#K3 = torch.cat((K2, K2), 0)

#Kernel = K3.view(2, 1, 3, 3)
#Kernel=K2.view(1,1,3,3)

output1 = F.conv2d(Input1, Kernel,padding=(1, 1))
#output2 = F.conv2d(Input2, Kernel,padding=(1, 1))
print(output1)
#print(output2)
#print(output1==output2)

#PROBLEME PAS CLAIR ICI, QUE JE LANCE OUTPUT 1 ET OUTPUT 2 SEPAREMENT ILS ONT DES VALEURS DIFFERENTES ET QUAND JE LES LANCE EN MEME TEMPS CA DONNE LA 
#MEME VALEUR HAHAHAH

#EN FAIT IL MANQUE IL PAIRE DE CROCHET AU KERNEL POUR EN FAIRE UN WEIGHT


tensor([[[[ 6.2017,  8.2447,  5.3671,  5.1891,  3.1120],
          [ 9.7478,  9.8756, 10.2343,  5.4568,  5.6541],
          [ 6.1095, 10.8441,  7.9513,  8.0344,  3.4512],
          [ 5.9866,  9.9754, 10.2208,  8.4889,  3.7277],
          [ 3.6821,  7.4000,  6.2894,  6.3021,  3.6070]]]])


MEME CNN UNE COUCHE AVEC EN ENTREE LA MEME IMAGE MAIS TOURNEE

In [77]:
#Input1 = torch.randn(5,5)
#print(Input)
#Input2=torch.rot90(Input1, 1, [1,0])
#Input3=Input2.view(1,1,5,5)
#print(Input1)
#print(Input3)
#CEST BON LIMAGE TOURRRNNNNNNNNNNNE AVEC VIEW MIS APRES
#print(Input)
#print(Input2)  # création de 2 inputs avec une rotation de 90° entre eux


#K=np.random.rand(3,3)
#K1 =  torch.Tensor(K)
#K2=invar(K1)
#print(K2)
#LE KERNEL EST BIEN INVARIANT PAR ROTATION
#K3 = torch.cat((K2, K2), 0)

#Kernel = K3.view(2, 1, 3, 3)
#Kernel = K2.view(1,1,3,3)
#output1 = F.conv2d(Input1, Kernel,padding=(1, 1))
output2 = F.conv2d(Input3, Kernel,padding=(1, 1))
#print(output1)
print(output2)
#print(output1==output2)


tensor([[[[ 3.6821,  5.9866,  6.1095,  9.7478,  6.2017],
          [ 7.4000,  9.9754, 10.8441,  9.8756,  8.2447],
          [ 6.2894, 10.2208,  7.9513, 10.2343,  5.3671],
          [ 6.3021,  8.4889,  8.0344,  5.4568,  5.1891],
          [ 3.6070,  3.7277,  3.4512,  5.6541,  3.1120]]]])


In [78]:
# AFFICHAGE DES IMAGES D'ORIGINE ET DES SORTIE DU CNN

print('image origine =')
print(Input1)
print('image tournée de 90°=')
print(Input2)

print('Sortie du CNN pour image origine =')
print(output1)
print('sortie du CNN pour image tournée de 90° =')
print(output2)

image origine =
tensor([[[[0.4758, 0.9870, 0.0251, 0.5356, 0.1434],
          [0.7508, 0.5020, 0.4327, 0.1075, 0.6955],
          [0.3193, 0.8840, 0.1034, 0.5053, 0.1011],
          [0.1812, 0.1135, 0.9581, 0.1798, 0.0447],
          [0.6730, 0.4051, 0.8607, 0.0169, 0.8984]]]])
image tournée de 90°=
tensor([[0.6730, 0.1812, 0.3193, 0.7508, 0.4758],
        [0.4051, 0.1135, 0.8840, 0.5020, 0.9870],
        [0.8607, 0.9581, 0.1034, 0.4327, 0.0251],
        [0.0169, 0.1798, 0.5053, 0.1075, 0.5356],
        [0.8984, 0.0447, 0.1011, 0.6955, 0.1434]])
Sortie du CNN pour image origine =
tensor([[[[ 6.2017,  8.2447,  5.3671,  5.1891,  3.1120],
          [ 9.7478,  9.8756, 10.2343,  5.4568,  5.6541],
          [ 6.1095, 10.8441,  7.9513,  8.0344,  3.4512],
          [ 5.9866,  9.9754, 10.2208,  8.4889,  3.7277],
          [ 3.6821,  7.4000,  6.2894,  6.3021,  3.6070]]]])
sortie du CNN pour image tournée de 90° =
tensor([[[[ 3.6821,  5.9866,  6.1095,  9.7478,  6.2017],
          [ 7.4000,  9.975

C'EST INVARIANT PAR ROTATION
IL RESTE DEMAIN A FAIRE UNE PETITE ROTATION DANS LAUTRE SENS ET MONTRER QUE CEST LES MEMES !!!!!!!!!! MAIS CA SE VOIT BIEN 

In [79]:
#ON COMPARE LES DEUX IMAGES EN LES FAISANT TOURNER

output1bis=output1.view(5,5) #j'enlève une paire de crochet pour retransformé en tensor puis en envoi dans la fonction qui fait tourner
output1tourne=torch.rot90(output1bis,1,[1,0]) # on fait tourner la sortie
outputcompare=output1tourne.view(1,1,5,5) # 
#print(output2)
#print(outputcompare)
output2np= output2.numpy()[0][0] # passage de torch à un numpy array et on enlève les crochet avec [0][0]
outputcomparenp= outputcompare.numpy()[0][0] 
output2npround=np.round(output2np,2) # arrondi à deux chiffres après la virgule car sinon le test d'égalité bug un peu 
outputcomparenpround=np.round(outputcomparenp,2)

#print(output2npround)
#print(outputcomparenpround)

print(output2npround==outputcomparenpround) # test d'égalité final




[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


TEST CREATION KERNEL TAILLE 3*3*2