QUESTIONS:
si on transforme notre kernel de base en un kernel multi symétrique on change l'effet du kernel ?
on devrait étudier le lien entre le kernel initial et celui transformé pour voir si ils ont les mêmes actions

IMPORT DES FONCTIONS IMPORTANTES

In [5]:
import torch
import torch.nn.functional as F
import torch.nn.utils.parametrize as parametrize
import numpy as np

TEST SUR LE ROT90

In [6]:
#TEST SUR LE TORCH.RAND
Input=torch.rand(2,2)
Input3=Input.view(1,1,2,2)
Input2=torch.rand(1,1,2,2)
Input4=Input2.view(2,2)
rot=torch.rot90(Input2,1,[1,0])
print(Input2)
print(Input4)

tensor([[[[0.1870, 0.5139],
          [0.8232, 0.1007]]]])
tensor([[0.1870, 0.5139],
        [0.8232, 0.1007]])


In [7]:
Input = torch.rand(5,5)
print(Input)
a=torch.rot90(Input, 1, [0, 1])
print(a)

#a = torch.arange(8).view(2, 2, 2)
#print(x)
#a=torch.rot90(x, 1, [1, 2])
#print(a)


tensor([[0.6095, 0.9009, 0.0628, 0.9988, 0.2177],
        [0.5391, 0.7443, 0.2524, 0.0031, 0.8613],
        [0.0232, 0.9158, 0.1274, 0.3924, 0.8788],
        [0.4317, 0.0669, 0.2779, 0.5404, 0.0555],
        [0.0759, 0.0151, 0.2402, 0.4712, 0.6888]])
tensor([[0.2177, 0.8613, 0.8788, 0.0555, 0.6888],
        [0.9988, 0.0031, 0.3924, 0.5404, 0.4712],
        [0.0628, 0.2524, 0.1274, 0.2779, 0.2402],
        [0.9009, 0.7443, 0.9158, 0.0669, 0.0151],
        [0.6095, 0.5391, 0.0232, 0.4317, 0.0759]])


TRANSFORMER UNE MATRICE EN UNE MATRICE SYMETRIQUE DE TOUTES DIRECTIONS

In [8]:
def invar(X):
    a=torch.rot90(X, 1, [1,0])
    b=torch.rot90(a, 1, [1,0])
    c=torch.rot90(b, 1, [1,0])
    d= X+a+b+c
    return(d)
K =  torch.Tensor([[1 ,0, -10],[2, 0 ,-2], [1, 0 ,-1]])

K1=np.random.rand(3,3)
K3 =  torch.Tensor(K1)
K4=invar(K3)
print(K4)



tensor([[2.2883, 1.1516, 2.2883],
        [1.1516, 2.2758, 1.1516],
        [2.2883, 1.1516, 2.2883]])


Compréhension des axes à rotater

In [9]:
#K =  torch.Tensor([[100 ,0, 0, 0,0 ],[0, 100 ,0, 0,0], [0, 0 ,100,0,0],[0, 0 ,0,100,0],[0, 0 ,0,0,100]])
#print(K)
#a=torch.rot90(K, 1, [1,0])
#print(a)
Input = torch.randn(5,5)
#print(Input)
Input2=torch.rot90(Input, 1, [1,0])
print(Input)
print(Input2)
print(Input==Input2)

tensor([[ 0.1828, -0.9258, -0.4833, -0.7715,  1.5429],
        [-1.7849, -0.7335, -1.8817,  0.2338,  0.6198],
        [ 1.2577, -0.1311, -0.0236,  0.2603,  0.1551],
        [ 0.3655,  0.1038, -1.1428, -1.4976, -0.8011],
        [ 1.9314, -0.4522, -0.4421,  0.8103,  0.2718]])
tensor([[ 1.9314,  0.3655,  1.2577, -1.7849,  0.1828],
        [-0.4522,  0.1038, -0.1311, -0.7335, -0.9258],
        [-0.4421, -1.1428, -0.0236, -1.8817, -0.4833],
        [ 0.8103, -1.4976,  0.2603,  0.2338, -0.7715],
        [ 0.2718, -0.8011,  0.1551,  0.6198,  1.5429]])
tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False,  True, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])


TEST CONV2D

In [11]:
Input = torch.rand(1,1,5,5)
#print(Input)
K =  torch.Tensor([[[1 ,0, -1],[2, 0 ,-10], [1, 0 ,-1]],[[1 ,0, -1],[2, 0 ,-10], [1, 0 ,-1]]])
#K=invar(K)
#K=invar(K)
print(K)
Kernel = K.view(2, 1, 3, 3)
print(Kernel)
output = F.conv2d(Input, Kernel)
#print(output)


tensor([[[  1.,   0.,  -1.],
         [  2.,   0., -10.],
         [  1.,   0.,  -1.]],

        [[  1.,   0.,  -1.],
         [  2.,   0., -10.],
         [  1.,   0.,  -1.]]])
tensor([[[[  1.,   0.,  -1.],
          [  2.,   0., -10.],
          [  1.,   0.,  -1.]]],


        [[[  1.,   0.,  -1.],
          [  2.,   0., -10.],
          [  1.,   0.,  -1.]]]])


cnn UNE COUCHE AVEC UNE IMAGE EN ENTREE

In [12]:
#Initialisation des images d'entrée et des kernels

#IMAGE DROITE
Input=torch.rand(5,5)
Input1 = Input.view(1,1,5,5)
print(Input1)


#IMAGE TOURNEE
Input2=torch.rot90(Input, 1, [1,0])
Input3=Input2.view(1,1,5,5)
print(Input3)


#KERNEL
K=np.random.rand(3,3)
K1 =  torch.Tensor(K)
K2=invar(K1)
Kernel=K2.view(1,1,3,3)
print(Kernel)




tensor([[[[0.1685, 0.9306, 0.7675, 0.8790, 0.1630],
          [0.2617, 0.3264, 0.2813, 0.3905, 0.9937],
          [0.3568, 0.7615, 0.0380, 0.6555, 0.1357],
          [0.1054, 0.2562, 0.4356, 0.6814, 0.6996],
          [0.0244, 0.3434, 0.0893, 0.2652, 0.1504]]]])
tensor([[[[0.0244, 0.1054, 0.3568, 0.2617, 0.1685],
          [0.3434, 0.2562, 0.7615, 0.3264, 0.9306],
          [0.0893, 0.4356, 0.0380, 0.2813, 0.7675],
          [0.2652, 0.6814, 0.6555, 0.3905, 0.8790],
          [0.1504, 0.6996, 0.1357, 0.9937, 0.1630]]]])
tensor([[[[1.9966, 1.4300, 1.9966],
          [1.4300, 1.1841, 1.4300],
          [1.9966, 1.4300, 1.9966]]]])


In [13]:
#Input1 = torch.randn(1,1,5,5)
#rint(Input1)
#Input2=torch.rot90(Input1, 1, [1,0])
#print(Input2)
#print(Input2)  # création de 2 inputs avec une rotation de 90° entre eux

#print(Input==Input2)
#K=np.random.rand(3,3)
#K1 =  torch.Tensor(K)
#K2=invar(K1)
#print(K2)

#K3 = torch.cat((K2, K2), 0)

#Kernel = K3.view(2, 1, 3, 3)
#Kernel=K2.view(1,1,3,3)

output1 = F.conv2d(Input1, Kernel,padding=(1, 1))
#output2 = F.conv2d(Input2, Kernel,padding=(1, 1))
print(output1)
#print(output2)
#print(output1==output2)

#PROBLEME PAS CLAIR ICI, QUE JE LANCE OUTPUT 1 ET OUTPUT 2 SEPAREMENT ILS ONT DES VALEURS DIFFERENTES ET QUAND JE LES LANCE EN MEME TEMPS CA DONNE LA 
#MEME VALEUR HAHAHAH

#EN FAIT IL MANQUE IL PAIRE DE CROCHET AU KERNEL POUR EN FAIRE UN WEIGHT


tensor([[[[2.5562, 3.9913, 5.3303, 5.4755, 3.6507],
          [4.9061, 6.2397, 8.9525, 6.6849, 5.2262],
          [3.1996, 4.4636, 6.4000, 7.3696, 5.6597],
          [3.2421, 3.6722, 6.0831, 4.5726, 4.0504],
          [1.1821, 2.0157, 3.4710, 3.8978, 2.9183]]]])


MEME CNN UNE COUCHE AVEC EN ENTREE LA MEME IMAGE MAIS TOURNEE

In [14]:
#Input1 = torch.randn(5,5)
#print(Input)
#Input2=torch.rot90(Input1, 1, [1,0])
#Input3=Input2.view(1,1,5,5)
#print(Input1)
#print(Input3)
#CEST BON LIMAGE TOURRRNNNNNNNNNNNE AVEC VIEW MIS APRES
#print(Input)
#print(Input2)  # création de 2 inputs avec une rotation de 90° entre eux


#K=np.random.rand(3,3)
#K1 =  torch.Tensor(K)
#K2=invar(K1)
#print(K2)
#LE KERNEL EST BIEN INVARIANT PAR ROTATION
#K3 = torch.cat((K2, K2), 0)

#Kernel = K3.view(2, 1, 3, 3)
#Kernel = K2.view(1,1,3,3)
#output1 = F.conv2d(Input1, Kernel,padding=(1, 1))
output2 = F.conv2d(Input3, Kernel,padding=(1, 1))
#print(output1)
print(output2)
#print(output1==output2)


tensor([[[[1.1821, 3.2421, 3.1996, 4.9061, 2.5562],
          [2.0157, 3.6722, 4.4636, 6.2397, 3.9913],
          [3.4710, 6.0831, 6.4000, 8.9525, 5.3303],
          [3.8978, 4.5726, 7.3696, 6.6849, 5.4755],
          [2.9183, 4.0504, 5.6597, 5.2262, 3.6507]]]])


In [15]:
print('image origine =')
print(Input1)
print('image tournée de 90°=')
print(Input2)

print('Sortie du CNN pour image origine =')
print(output1)
print('sortie du CNN pour image tournée de 90° =')
print(output2)

image origine =
tensor([[[[0.1685, 0.9306, 0.7675, 0.8790, 0.1630],
          [0.2617, 0.3264, 0.2813, 0.3905, 0.9937],
          [0.3568, 0.7615, 0.0380, 0.6555, 0.1357],
          [0.1054, 0.2562, 0.4356, 0.6814, 0.6996],
          [0.0244, 0.3434, 0.0893, 0.2652, 0.1504]]]])
image tournée de 90°=
tensor([[0.0244, 0.1054, 0.3568, 0.2617, 0.1685],
        [0.3434, 0.2562, 0.7615, 0.3264, 0.9306],
        [0.0893, 0.4356, 0.0380, 0.2813, 0.7675],
        [0.2652, 0.6814, 0.6555, 0.3905, 0.8790],
        [0.1504, 0.6996, 0.1357, 0.9937, 0.1630]])
Sortie du CNN pour image origine =
tensor([[[[2.5562, 3.9913, 5.3303, 5.4755, 3.6507],
          [4.9061, 6.2397, 8.9525, 6.6849, 5.2262],
          [3.1996, 4.4636, 6.4000, 7.3696, 5.6597],
          [3.2421, 3.6722, 6.0831, 4.5726, 4.0504],
          [1.1821, 2.0157, 3.4710, 3.8978, 2.9183]]]])
sortie du CNN pour image tournée de 90° =
tensor([[[[1.1821, 3.2421, 3.1996, 4.9061, 2.5562],
          [2.0157, 3.6722, 4.4636, 6.2397, 3.9913],
    

C'EST INVARIANT PAR ROTATION
IL RESTE DEMAIN A FAIRE UNE PETITE ROTATION DANS LAUTRE SENS ET MONTRER QUE CEST LES MEMES !!!!!!!!!! MAIS CA SE VOIT BIEN 

In [17]:
#ON COMPARE LES DEUX IMAGES EN LES FAISANT TOURNER

output1bis=output1.view(5,5)
output1tourne=torch.rot90(output1bis,1,[1,0])
outputcompare=output1tourne.view(1,1,5,5)
print(outputcompare==output2)

tensor([[[[ True,  True, False, False, False],
          [ True,  True,  True, False, False],
          [ True,  True, False, False,  True],
          [ True,  True, False,  True,  True],
          [False,  True,  True,  True,  True]]]])


LA SORTIE NEST PAS LA MEME SORTIE QUE LAUTRE AVEC UNE ROTATION PRB AVEC LES KERNELS EN ENTREE PCQ ON PRENDS DES KERNELS 332 POUR QUE CA MARCHE MAIS JSP POURQUOI

TEST CREATION KERNEL TAILLE 3*3*2

In [ ]:
K=np.random.rand(3,3)
print(K)
K1 =  torch.Tensor([K,K])
#K=invar(K)

[[0.65629061 0.03921562 0.32412561]
 [0.15907867 0.27573221 0.41600818]
 [0.73929109 0.37389222 0.61402763]]


In [ ]:
nb_channels = 1
h, w = 5, 5
x = torch.randn(1, nb_channels, h, w)
print(x)
weights = torch.tensor([[[0., 0., 0.],
                         [0., 1., 0.],
                         [0., 0., 0.]],
                        [[0., 0., 0.],
                         [0., 1., 0.],
                         [0., 0., 0.]]])
weights = weights.view(2, 1, 3, 3)
print(weights)
output = F.conv2d(x, weights)

tensor([[[[ 0.9197,  0.6246, -0.5283,  0.3123, -0.2951],
          [-0.9506, -0.8133, -0.7338,  0.2097,  0.0402],
          [-1.3254,  0.3065,  0.5334,  0.5418, -0.7939],
          [-0.2235,  0.9542,  0.4922,  0.2611,  0.8706],
          [ 0.1989, -0.4099,  0.9503, -0.2401, -0.2681]]]])
tensor([[[[0., 0., 0.],
          [0., 1., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 1., 0.],
          [0., 0., 0.]]]])
