QUESTIONS:
si on transforme notre kernel de base en un kernel multi symétrique on change l'effet du kernel ?
on devrait étudier le lien entre le kernel initial et celui transformé pour voir si ils ont les mêmes actions

IMPORT DES FONCTIONS IMPORTANTES

In [150]:
import torch
import torch.nn.functional as F
import torch.nn.utils.parametrize as parametrize
import numpy as np

TEST SUR LE ROT90

In [196]:
Input = torch.rand(5,5)
print(Input)
a=torch.rot90(Input, 1, [0, 1])
print(a)


#a = torch.arange(8).view(2, 2, 2)
#print(x)
#a=torch.rot90(x, 1, [1, 2])
#print(a)


tensor([[0.0085, 0.2894, 0.9292, 0.9241, 0.5100],
        [0.2858, 0.9247, 0.4278, 0.7100, 0.4945],
        [0.5073, 0.2231, 0.4989, 0.9818, 0.1270],
        [0.5282, 0.1926, 0.1051, 0.6493, 0.9612],
        [0.2835, 0.7807, 0.6888, 0.8328, 0.5585]])
tensor([[0.5100, 0.4945, 0.1270, 0.9612, 0.5585],
        [0.9241, 0.7100, 0.9818, 0.6493, 0.8328],
        [0.9292, 0.4278, 0.4989, 0.1051, 0.6888],
        [0.2894, 0.9247, 0.2231, 0.1926, 0.7807],
        [0.0085, 0.2858, 0.5073, 0.5282, 0.2835]])


TRANSFORMER UNE MATRICE EN UNE MATRICE SYMETRIQUE DE TOUTES DIRECTIONS

In [174]:
def invar(X):
    a=torch.rot90(X, 1, [1,0])
    b=torch.rot90(a, 1, [1,0])
    c=torch.rot90(b, 1, [1,0])
    d= X+a+b+c
    return(d)
K =  torch.Tensor([[1 ,0, -10],[2, 0 ,-2], [1, 0 ,-1]])

K1=np.random.rand(3,3)
K3 =  torch.Tensor(K1)
K4=invar(K3)
print(K4)



tensor([[2.1882, 2.8908, 2.1882],
        [2.8908, 3.6414, 2.8908],
        [2.1882, 2.8908, 2.1882]])


Compréhension des axes à rotater

In [95]:
#K =  torch.Tensor([[100 ,0, 0, 0,0 ],[0, 100 ,0, 0,0], [0, 0 ,100,0,0],[0, 0 ,0,100,0],[0, 0 ,0,0,100]])
#print(K)
#a=torch.rot90(K, 1, [1,0])
#print(a)
Input = torch.randn(5,5)
#print(Input)
Input2=torch.rot90(Input, 1, [1,0])
print(Input)
print(Input2)
print(Input==Input2)

tensor([[ 2.2037e+00, -6.2239e-02, -1.4695e+00,  9.8689e-02, -1.0891e+00],
        [-2.5783e-01, -2.2005e-03,  1.6597e+00,  7.6363e-01,  3.1358e-01],
        [ 8.8062e-01,  6.8853e-02, -2.0420e-01, -6.7099e-01, -1.2425e+00],
        [ 9.3897e-01, -1.9173e-01, -1.3197e+00, -1.6838e-01, -1.0084e+00],
        [ 3.7878e-01, -6.2646e-01, -3.0756e-01,  1.0493e+00, -3.6613e-01]])
tensor([[ 3.7878e-01,  9.3897e-01,  8.8062e-01, -2.5783e-01,  2.2037e+00],
        [-6.2646e-01, -1.9173e-01,  6.8853e-02, -2.2005e-03, -6.2239e-02],
        [-3.0756e-01, -1.3197e+00, -2.0420e-01,  1.6597e+00, -1.4695e+00],
        [ 1.0493e+00, -1.6838e-01, -6.7099e-01,  7.6363e-01,  9.8689e-02],
        [-3.6613e-01, -1.0084e+00, -1.2425e+00,  3.1358e-01, -1.0891e+00]])
tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False,  True, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])


TEST CONV2D

In [148]:
Input = torch.rand(1,1,5,5)
#print(Input)
K =  torch.Tensor([[[1 ,0, -1],[2, 0 ,-10], [1, 0 ,-1]],[[1 ,0, -1],[2, 0 ,-10], [1, 0 ,-1]]])
#K=invar(K)
#K=invar(K)
print(K)
#Kernel = K.view(2, 1, 3, 3)
print(Kernel)
output = F.conv2d(Input, Kernel)
#print(output)


tensor([[[  1.,   0.,  -1.],
         [  2.,   0., -10.],
         [  1.,   0.,  -1.]],

        [[  1.,   0.,  -1.],
         [  2.,   0., -10.],
         [  1.,   0.,  -1.]]])
tensor([[[[  1.,   0.,  -1.],
          [  2.,   0., -10.],
          [  1.,   0.,  -1.]]],


        [[[  1.,   0.,  -1.],
          [  2.,   0., -10.],
          [  1.,   0.,  -1.]]]])


cnn UNE COUCHE AVEC UNE IMAGE EN ENTREE

In [209]:
Input1 = torch.randn(1,1,5,5)
print(Input1)
Input2=torch.rot90(Input1, 1, [1,0])
print(Input2)
#print(Input2)  # création de 2 inputs avec une rotation de 90° entre eux

print(Input==Input2)
K=np.random.rand(3,3)
K1 =  torch.Tensor(K)
K2=invar(K1)
print(K2)

K3 = torch.cat((K2, K2), 0)

Kernel = K3.view(2, 1, 3, 3)


output1 = F.conv2d(Input1, Kernel,padding=(1, 1))
#output2 = F.conv2d(Input2, Kernel,padding=(1, 1))
print(output1)
#print(output2)
#print(output1==output2)

#PROBLEME PAS CLAIR ICI, QUE JE LANCE OUTPUT 1 ET OUTPUT 2 SEPAREMENT ILS ONT DES VALEURS DIFFERENTES ET QUAND JE LES LANCE EN MEME TEMPS CA DONNE LA 
#MEME VALEUR HAHAHAH

#EN FAIT IL MANQUE IL PAIRE DE CROCHET AU KERNEL POUR EN FAIRE UN WEIGHT


tensor([[[[-0.3306, -0.3657,  1.0506,  0.1914,  1.3812],
          [-1.8576, -1.0224,  2.4073,  0.3515, -0.1223],
          [ 0.4758,  0.1745,  0.6395, -1.1648, -0.2823],
          [-0.1166,  0.5802,  2.7676, -1.3387,  2.3266],
          [-1.7379,  1.0903, -0.1181, -1.6033, -0.6716]]]])
tensor([[[[-0.3306, -0.3657,  1.0506,  0.1914,  1.3812],
          [-1.8576, -1.0224,  2.4073,  0.3515, -0.1223],
          [ 0.4758,  0.1745,  0.6395, -1.1648, -0.2823],
          [-0.1166,  0.5802,  2.7676, -1.3387,  2.3266],
          [-1.7379,  1.0903, -0.1181, -1.6033, -0.6716]]]])
tensor([[[[False, False, False, False, False],
          [False, False, False, False, False],
          [False, False, False, False, False],
          [False, False, False, False, False],
          [False, False, False, False, False]]]])
tensor([[1.5087, 1.2335, 1.5087],
        [1.2335, 0.6850, 1.2335],
        [1.5087, 1.2335, 1.5087]])
tensor([[[[-4.5115,  0.2058,  2.4618,  7.0117,  1.5616],
          [-2.6430,  2.510

MEME CNN UNE COUCHE AVEC EN ENTREE LA MEME IMAGE MAIS TOURNEE

In [192]:
#Input1 = torch.randn(1,1,5,5)
#print(Input)
Input2=torch.rot90(Input1, 1, [1,0])
#print(Input)
#print(Input2)  # création de 2 inputs avec une rotation de 90° entre eux

print(Input==Input2)
K=np.random.rand(3,3)
K1 =  torch.Tensor(K)
K2=invar(K1)
print(K2)

K3 = torch.cat((K2, K2), 0)

Kernel = K3.view(2, 1, 3, 3)

#output1 = F.conv2d(Input1, Kernel,padding=(1, 1))
output2 = F.conv2d(Input2, Kernel,padding=(1, 1))
#print(output1)
print(output2)
#print(output1==output2)

tensor([[[[False, False, False, False, False],
          [False, False, False, False, False],
          [False, False, False, False, False],
          [False, False, False, False, False],
          [False, False, False, False, False]]]])
tensor([[2.1081, 2.8035, 2.1081],
        [2.8035, 2.7968, 2.8035],
        [2.1081, 2.8035, 2.1081]])
tensor([[[[ 0.7570, -2.8612,  2.1183,  3.3515,  6.4372],
          [ 5.6245, -1.4128, -2.2566,  1.5880,  7.1522],
          [ 6.7333,  2.8352, -2.0050,  5.6551,  7.6406],
          [ 8.0148,  1.5466, -8.5384, -5.7123, -0.3565],
          [ 2.1064, -5.5245, -4.8995, -7.0815, -0.7607]],

         [[ 0.7570, -2.8612,  2.1183,  3.3515,  6.4372],
          [ 5.6245, -1.4128, -2.2566,  1.5880,  7.1522],
          [ 6.7333,  2.8352, -2.0050,  5.6551,  7.6406],
          [ 8.0148,  1.5466, -8.5384, -5.7123, -0.3565],
          [ 2.1064, -5.5245, -4.8995, -7.0815, -0.7607]]]])


LA SORTIE NEST PAS LA MEME SORTIE QUE LAUTRE AVEC UNE ROTATION PRB AVEC LES KERNELS EN ENTREE PCQ ON PRENDS DES KERNELS 332 POUR QUE CA MARCHE MAIS JSP POURQUOI

TEST CREATION KERNEL TAILLE 3*3*2

In [153]:
K=np.random.rand(3,3)
print(K)
K1 =  torch.Tensor([K,K])
#K=invar(K)


[[0.44963187 0.14531515 0.77562163]
 [0.1096695  0.03654071 0.92070671]
 [0.86433302 0.39023179 0.14198664]]


In [156]:
nb_channels = 1
h, w = 5, 5
x = torch.randn(1, nb_channels, h, w)
print(x)
weights = torch.tensor([[[0., 0., 0.],
                         [0., 1., 0.],
                         [0., 0., 0.]],
                        [[0., 0., 0.],
                         [0., 1., 0.],
                         [0., 0., 0.]]])
weights = weights.view(2, 1, 3, 3)
print(weights)
output = F.conv2d(x, weights)

tensor([[[[ 1.2492,  2.8971, -0.2221, -0.1074, -0.5605],
          [ 0.5684,  0.7354, -0.8335,  0.1157, -1.8499],
          [-2.0530,  1.8674,  0.5720, -0.8691,  0.6071],
          [-0.4218, -0.6412,  1.6308,  0.3638, -0.0115],
          [ 0.7344, -0.1123, -0.0140,  0.8240,  1.7946]]]])
tensor([[[[0., 0., 0.],
          [0., 1., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 1., 0.],
          [0., 0., 0.]]]])


NN ENTIER DANS UNE CLASSE AVEC UNE COUCHE CONV ET UNE COUCHE FULLY CONNECTED

In [ ]:
class Network(nn.Module):
    def __init__(self):
        super(Network,self).__init__()
        self.conv1=NN.Conv2d(in_channels=1,out_channels=6, kernel_size=5)
        self.fc1=nn.Linear(in_features=12*4*4, out_features=128) # un couche fully connected pour faire de la classification, pour l'instant pas besoin, on travaille juste sur les kernels
    def forward(self,t):
        return t


In [ ]:
network= Network()