excellent


IMPORT DES FONCTIONS IMPORTANTES

In [20]:
import torch
import torch.nn.functional as F
import torch.nn.utils.parametrize as parametrize

TEST SUR LE ROT90

In [42]:
Input = torch.rand(1,1,5,5)
print(Input)
a=torch.rot90(Input, 1, [1, 0])
print(a)


#a = torch.arange(8).view(2, 2, 2)
#print(x)
#a=torch.rot90(x, 1, [1, 2])
#print(a)


tensor([[[[0.0405, 0.7857, 0.9461, 0.5791, 0.0337],
          [0.9431, 0.0749, 0.7477, 0.9794, 0.5436],
          [0.7670, 0.6457, 0.4116, 0.8537, 0.8184],
          [0.9779, 0.4518, 0.6958, 0.2105, 0.1977],
          [0.2524, 0.3839, 0.8664, 0.9085, 0.9512]]]])
tensor([[[[0.0405, 0.7857, 0.9461, 0.5791, 0.0337],
          [0.9431, 0.0749, 0.7477, 0.9794, 0.5436],
          [0.7670, 0.6457, 0.4116, 0.8537, 0.8184],
          [0.9779, 0.4518, 0.6958, 0.2105, 0.1977],
          [0.2524, 0.3839, 0.8664, 0.9085, 0.9512]]]])


TRANSFORMER UNE MATRICE EN UNE MATRICE SYMETRIQUE DE TOUTES DIRECTIONS

In [44]:
def invar(X):
    a=torch.rot90(X, 1, [0,1])
    b=torch.rot90(a, 1, [0,1])
    c=torch.rot90(b, 1, [0,1])
    d= X+a+b+c
    return(d)
K =  torch.Tensor([[1 ,0, -10],[2, 0 ,-2], [1, 0 ,-1]])
print(invar(K))

    



tensor([[-9.,  0., -9.],
        [ 0.,  0.,  0.],
        [-9.,  0., -9.]])


TEST CONV2D

In [19]:
Input = torch.rand(1,1,5,5)
print(Input)
K =  torch.Tensor([[[1 ,0, -1],[2, 0 ,-2], [1, 0 ,-1]],[[1 ,0, -1],[2, 0 ,-2], [1, 0 ,-1]]])

print(K)
Kernel = K.view(2, 1, 3, 3)
output = F.conv2d(Input, Kernel)
print(output)


tensor([[[[0.0961, 0.0726, 0.5731, 0.1828, 0.7097, 0.6952, 0.9535, 0.8780,
           0.3641],
          [0.4038, 0.4974, 0.4809, 0.0519, 0.5104, 0.7189, 0.4521, 0.7233,
           0.7596],
          [0.7744, 0.4119, 0.0273, 0.2817, 0.8605, 0.0663, 0.4444, 0.0473,
           0.9345],
          [0.5829, 0.7222, 0.7312, 0.2815, 0.0667, 0.9448, 0.9163, 0.4362,
           0.2136],
          [0.7029, 0.4735, 0.4043, 0.1886, 0.0933, 0.9224, 0.1128, 0.4075,
           0.0108],
          [0.4593, 0.0191, 0.7739, 0.2862, 0.0405, 0.2450, 0.5683, 0.2545,
           0.5674],
          [0.1363, 0.1444, 0.5725, 0.0680, 0.8148, 0.3932, 0.2474, 0.8904,
           0.7970],
          [0.7082, 0.5084, 0.4547, 0.4107, 0.2951, 0.0447, 0.1840, 0.6719,
           0.1362],
          [0.4016, 0.9483, 0.4913, 0.3217, 0.1108, 0.1317, 0.4269, 0.4023,
           0.1529],
          [0.5815, 0.8767, 0.7627, 0.0869, 0.2983, 0.6472, 0.4244, 0.8774,
           0.0776]]]])
tensor([[[ 1.,  0., -1.],
         [ 2.,  0., -

In [10]:
nb_channels = 1
h, w = 5, 5
x = torch.randn(1, nb_channels, h, w)
weights = torch.tensor([[[0., 0., 0.],
                         [0., 1., 0.],
                         [0., 0., 0.]],
                        [[0., 0., 0.],
                         [0., 1., 0.],
                         [0., 0., 0.]]])
weights = weights.view(2, 1, 3, 3)

output = F.conv2d(x, weights)

NN ENTIER DANS UNE CLASSE AVEC UNE COUCHE CONV ET UNE COUCHE FULLY CONNECTED

In [ ]:
class Network(nn.Module):
    def __init__(self):
        super(Network,self).__init__()
        self.conv1=NN.Conv2d(in_channels=1,out_channels=6, kernel_size=5)
        self.fc1=nn.Linear(in_features=12*4*4, out_features=128) # un couche fully connected pour faire de la classification, pour l'instant pas besoin, on travaille juste sur les kernels
    def forward(self,t):
        return t


In [ ]:
network= Network()