QUESTIONS:
si on transforme notre kernel de base en un kernel multi symétrique on change l'effet du kernel ?
on devrait étudier le lien entre le kernel initial et celui transformé pour voir si ils ont les mêmes actions

IMPORT DES FONCTIONS IMPORTANTES

In [24]:
import torch
import torch.nn.functional as F
import torch.nn.utils.parametrize as parametrize
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

Création d'une base de donnée intéressante

TRANSFORMER UNE MATRICE EN UNE MATRICE SYMETRIQUE DE TOUTES DIRECTIONS

In [25]:
def invar(X):
    a=torch.rot90(X, 1, [1,0])
    b=torch.rot90(a, 1, [1,0])
    c=torch.rot90(b, 1, [1,0])
    d= X+a+b+c
    return(d)



tensor([[  1.,   0., -10.],
        [  2.,   0.,  -2.],
        [  1.,   0.,  -1.]])
tensor([[-9.,  0., -9.],
        [ 0.,  0.,  0.],
        [-9.,  0., -9.]])


cnn UNE COUCHE AVEC UNE IMAGE EN ENTREE

In [28]:
#Initialisation des images d'entrée et des kernels

#IMAGE DROITE
Input=torch.rand(5,5)
Input1 = Input.view(1,1,5,5)
print(Input1)


#IMAGE TOURNEE
Input2=torch.rot90(Input, 1, [1,0])
Input3=Input2.view(1,1,5,5)
print(Input3)


#KERNEL
K=np.random.rand(3,3)
K1 =  torch.Tensor(K)
K2=invar(K1)
Kernel=K2.view(1,1,3,3)
print(Kernel)




tensor([[[[0.9377, 0.6152, 0.9357, 0.5170, 0.6549],
          [0.3172, 0.4478, 0.3516, 0.5399, 0.4602],
          [0.0376, 0.5399, 0.8279, 0.4422, 0.8943],
          [0.0546, 0.7707, 0.1115, 0.6074, 0.8308],
          [0.3144, 0.1282, 0.7810, 0.8668, 0.6794]]]])
tensor([[[[0.3144, 0.0546, 0.0376, 0.3172, 0.9377],
          [0.1282, 0.7707, 0.5399, 0.4478, 0.6152],
          [0.7810, 0.1115, 0.8279, 0.3516, 0.9357],
          [0.8668, 0.6074, 0.4422, 0.5399, 0.5170],
          [0.6794, 0.8308, 0.8943, 0.4602, 0.6549]]]])
tensor([[[[2.1828, 2.7560, 2.1828],
          [2.7560, 1.7614, 2.7560],
          [2.1828, 2.7560, 2.1828]]]])


In [29]:
#Input1 = torch.randn(1,1,5,5)
#rint(Input1)
#Input2=torch.rot90(Input1, 1, [1,0])
#print(Input2)
#print(Input2)  # création de 2 inputs avec une rotation de 90° entre eux

#print(Input==Input2)
#K=np.random.rand(3,3)
#K1 =  torch.Tensor(K)
#K2=invar(K1)
#print(K2)

#K3 = torch.cat((K2, K2), 0)

#Kernel = K3.view(2, 1, 3, 3)
#Kernel=K2.view(1,1,3,3)

output1 = F.conv2d(Input1, Kernel,padding=(1, 1))
#output2 = F.conv2d(Input2, Kernel,padding=(1, 1))
print(output1)
#print(output2)
#print(output1==output2)

#PROBLEME PAS CLAIR ICI, QUE JE LANCE OUTPUT 1 ET OUTPUT 2 SEPAREMENT ILS ONT DES VALEURS DIFFERENTES ET QUAND JE LES LANCE EN MEME TEMPS CA DONNE LA 
#MEME VALEUR HAHAHAH

#EN FAIT IL MANQUE IL PAIRE DE CROCHET AU KERNEL POUR EN FAIRE UN WEIGHT


tensor([[[[ 5.1988,  8.9408,  7.8935,  8.5546,  5.0253],
          [ 7.0020, 11.7938, 12.8173, 13.0633,  8.6621],
          [ 5.2386,  8.5170, 10.6056, 12.5165,  8.8566],
          [ 4.6485,  7.9370, 12.7445, 14.2219, 10.3318],
          [ 2.7399,  5.7315,  7.4335,  9.2828,  7.2012]]]])


MEME CNN UNE COUCHE AVEC EN ENTREE LA MEME IMAGE MAIS TOURNEE

In [30]:
#Input1 = torch.randn(5,5)
#print(Input)
#Input2=torch.rot90(Input1, 1, [1,0])
#Input3=Input2.view(1,1,5,5)
#print(Input1)
#print(Input3)
#CEST BON LIMAGE TOURRRNNNNNNNNNNNE AVEC VIEW MIS APRES
#print(Input)
#print(Input2)  # création de 2 inputs avec une rotation de 90° entre eux


#K=np.random.rand(3,3)
#K1 =  torch.Tensor(K)
#K2=invar(K1)
#print(K2)
#LE KERNEL EST BIEN INVARIANT PAR ROTATION
#K3 = torch.cat((K2, K2), 0)

#Kernel = K3.view(2, 1, 3, 3)
#Kernel = K2.view(1,1,3,3)
#output1 = F.conv2d(Input1, Kernel,padding=(1, 1))
output2 = F.conv2d(Input3, Kernel,padding=(1, 1))
#print(output1)
print(output2)
#print(output1==output2)


tensor([[[[ 2.7399,  4.6485,  5.2386,  7.0020,  5.1988],
          [ 5.7315,  7.9370,  8.5170, 11.7938,  8.9408],
          [ 7.4335, 12.7445, 10.6056, 12.8173,  7.8935],
          [ 9.2828, 14.2219, 12.5165, 13.0633,  8.5546],
          [ 7.2012, 10.3318,  8.8566,  8.6621,  5.0253]]]])


In [31]:
# AFFICHAGE DES IMAGES D'ORIGINE ET DES SORTIE DU CNN

print('image origine =')
print(Input1)
print('image tournée de 90°=')
print(Input2)

print('Sortie du CNN pour image origine =')
print(output1)
print('sortie du CNN pour image tournée de 90° =')
print(output2)

image origine =
tensor([[[[0.9377, 0.6152, 0.9357, 0.5170, 0.6549],
          [0.3172, 0.4478, 0.3516, 0.5399, 0.4602],
          [0.0376, 0.5399, 0.8279, 0.4422, 0.8943],
          [0.0546, 0.7707, 0.1115, 0.6074, 0.8308],
          [0.3144, 0.1282, 0.7810, 0.8668, 0.6794]]]])
image tournée de 90°=
tensor([[0.3144, 0.0546, 0.0376, 0.3172, 0.9377],
        [0.1282, 0.7707, 0.5399, 0.4478, 0.6152],
        [0.7810, 0.1115, 0.8279, 0.3516, 0.9357],
        [0.8668, 0.6074, 0.4422, 0.5399, 0.5170],
        [0.6794, 0.8308, 0.8943, 0.4602, 0.6549]])
Sortie du CNN pour image origine =
tensor([[[[ 5.1988,  8.9408,  7.8935,  8.5546,  5.0253],
          [ 7.0020, 11.7938, 12.8173, 13.0633,  8.6621],
          [ 5.2386,  8.5170, 10.6056, 12.5165,  8.8566],
          [ 4.6485,  7.9370, 12.7445, 14.2219, 10.3318],
          [ 2.7399,  5.7315,  7.4335,  9.2828,  7.2012]]]])
sortie du CNN pour image tournée de 90° =
tensor([[[[ 2.7399,  4.6485,  5.2386,  7.0020,  5.1988],
          [ 5.7315,  7.937

C'EST INVARIANT PAR ROTATION
IL RESTE DEMAIN A FAIRE UNE PETITE ROTATION DANS LAUTRE SENS ET MONTRER QUE CEST LES MEMES !!!!!!!!!! MAIS CA SE VOIT BIEN 

In [32]:
#ON COMPARE LES DEUX IMAGES EN LES FAISANT TOURNER

output1bis=output1.view(5,5) #j'enlève une paire de crochet pour retransformé en tensor puis en envoi dans la fonction qui fait tourner
output1tourne=torch.rot90(output1bis,1,[1,0]) # on fait tourner la sortie
outputcompare=output1tourne.view(1,1,5,5) # 
#print(output2)
#print(outputcompare)
output2np= output2.numpy()[0][0] # passage de torch à un numpy array et on enlève les crochet avec [0][0]
outputcomparenp= outputcompare.numpy()[0][0] 
output2npround=np.round(output2np,2) # arrondi à deux chiffres après la virgule car sinon le test d'égalité bug un peu 
outputcomparenpround=np.round(outputcomparenp,2)

#print(output2npround)
#print(outputcomparenpround)

print(output2npround==outputcomparenpround) # test d'égalité final




[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


TEST CREATION KERNEL TAILLE 3*3*2